global:
 message: Welcome to customer service prod environment
server:
 port: 8082
message: Hello from Customer Prod
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/cust-prod
  username: root
  password:
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true   